#!/bin/bash

GITHUB_USERNAME=gergelynagyvari
REPO_NAME=dotfiles
REPO_URL=https://github.com/gergelynagyvari/dotfiles.git 

INSTALL_DIR=projects/dotfiles

# Functions
install_tmux() {
    echo "--- Configuring tmux ---"
    sudo yum -y install tmux
    cp -fs $HOME/$INSTALL_DIR/tmux/tmux.conf $HOME/.tmux.conf
}

install_vim() {
    echo "--- Configuring vim ---"
    sudo yum -y install vim
    cp -fs $HOME/$INSTALL_DIR/vim/vimrc $HOME/.vimrc
}

get_files_and_config() {
    echo "--- Cloning configuration files ---"
    git clone $REPO_URL $INSTALL_DIR
    cd $INSTALL_DIR
    git checkout master
    git pull
}

expand_bashrc() {
    echo "--- Expanding bashrc of user ---"
    cat $HOME/$INSTALL_DIR/bashrc/bashrc >>~/.bashrc
    echo ". ~/projects/dotfiles/bash_prompt.sh" >>~/.bashrc
    echo "New bashrc config:"
    cat ~/.bashrc
}

add_ssh_keys() {
    echo "--- Installing SSH keys ---"
    cp $HOME/shared/openssh_key_private.ppk ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    eval $(ssh-agent)
    ssh-add ~/.ssh/id_rsa
}

set_git_config() {
    echo "--- Setting up git config ---"
    if [ ! -f ~/.gitconfig ]; then
        echo "No previous git configuration found, initializing git user data:"
        echo "What is you name?"
        read -e USER_NAME
        echo "What is your email address?"
        read -e USER_EMAIL
        echo -e "[user]\n    name = $USER_NAME\n    email = $USER_EMAIL\n" >>~/.gitconfig
    fi
    cat $HOME/$INSTALL_DIR/git/gitconfig >>~/.gitconfig
}

# Setup script

echo '------------------------------------------------------------'
echo 'Starting setup script...'
echo '------------------------------------------------------------'
 
if [ "$(pwd)" = "$HOME/$INSTALL_DIR" ]; then 
    echo "Not allowed to run this script from your HOME/dotfiles folder!"
    echo ''
    exit
fi

if [ -d "$HOME/$INSTALL_DIR" ]; then 
    while true; do
        echo "Existing configuration is detected in the following folder:"
        echo "$HOME/$INSTALL_DIR"
        echo "It must be removed to continue. (d)elete it (a)bort or (i)gnore?"

        read -n 1 action

        case "$action" in
            d ) echo "Deleting previous configuration ($HOME/$INSTALL_DIR)"
                rm -rf $HOME/$INSTALL_DIR
                break
                ;;
            a ) echo "Aborting exectution"
                exit
                ;;
            i ) echo "Ignore and continue"
                break
                ;;
            * ) echo "Wrong answer, chose one from above."
                ;;
        esac
    done
fi

#add_ssh_keys
#get_files_and_config
#set_git_config
install_tmux
install_vim
expand_bashrc

echo '------------------------------------------------------------'
echo 'Finished setup script.'
echo '------------------------------------------------------------'
